### PR TITLE
3.0.3

### PR DESCRIPTION
**Pull request by jtsternberg**
* Fix bug where post-types with`'exclude_from_search' => true` would not be properly connected.
* Add filter, `gathercontent_mapping_post_types`, for ability to filter allowed post-types for mapping.
* Add GatherContent plugin settings link to inline action links on plugin page.

### CODE REVIEW

**Comment by jtsternberg** [comment]
bump.

**Comment by jtsternberg** [comment]
This now also includes 3.0.4 changes as well.

### 3.0.4 ###
* Update to complement the 3.0.0.8 release to make sure that the minimum 1.8.3 version of underscore is loaded early so that it works when SCRIPT_DEBUG is disabled.
* Fix bug where GatherContent admin column and metabox would not display for a mapped post-type occasionally (if the mapping was imported, or when it is first created).

**Comment by jtsternberg** [comment]
bump.

**Comment by Cyapow** [comment]
Sorry was on paternity leave haha. Will merge now

**Comment by jtsternberg** [comment]
Well congratulations!

**Pull request merged**
